/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectointegrador;

/**
 *
 * @author MI HP
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LupaIcono = new javax.swing.JLabel();
        ReservaRestauranTXT = new javax.swing.JLabel();
        NombreEmpresaTXT = new javax.swing.JLabel();
        EstatusTXT = new javax.swing.JLabel();
        BarraBusqueda = new javax.swing.JTextField();
        AvionIcono = new javax.swing.JLabel();
        AgenciaViajesTXT = new javax.swing.JLabel();
        SalirTXT = new javax.swing.JLabel();
        VentaPasajesTXT = new javax.swing.JLabel();
        EnvioEncomiendaTXT = new javax.swing.JLabel();
        PaquetesTuristicosTXT = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(34, 45, 49));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LupaIcono.setBackground(new java.awt.Color(54, 73, 80));
        LupaIcono.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        LupaIcono.setForeground(new java.awt.Color(255, 255, 255));
        LupaIcono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LupaIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_search_20px.png"))); // NOI18N
        jPanel2.add(LupaIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 20, 30));

        ReservaRestauranTXT.setBackground(new java.awt.Color(54, 127, 168));
        ReservaRestauranTXT.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        ReservaRestauranTXT.setForeground(new java.awt.Color(255, 255, 255));
        ReservaRestauranTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReservaRestauranTXT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_restaurant_30px.png"))); // NOI18N
        ReservaRestauranTXT.setText("Reservaciones a restaurantes");
        ReservaRestauranTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(ReservaRestauranTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 220, 30));

        NombreEmpresaTXT.setBackground(new java.awt.Color(54, 127, 168));
        NombreEmpresaTXT.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        NombreEmpresaTXT.setForeground(new java.awt.Color(255, 255, 255));
        NombreEmpresaTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NombreEmpresaTXT.setText("PurpleTeam");
        NombreEmpresaTXT.setOpaque(true);
        jPanel2.add(NombreEmpresaTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 40));

        EstatusTXT.setBackground(new java.awt.Color(54, 127, 168));
        EstatusTXT.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        EstatusTXT.setForeground(new java.awt.Color(0, 255, 0));
        EstatusTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EstatusTXT.setText("Online");
        jPanel2.add(EstatusTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 150, 20));

        BarraBusqueda.setEditable(false);
        BarraBusqueda.setBackground(new java.awt.Color(54, 73, 80));
        BarraBusqueda.setBorder(null);
        jPanel2.add(BarraBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 190, 30));

        AvionIcono.setBackground(new java.awt.Color(54, 127, 168));
        AvionIcono.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        AvionIcono.setForeground(new java.awt.Color(255, 255, 255));
        AvionIcono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AvionIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_airplane_take_off_30px.png"))); // NOI18N
        jPanel2.add(AvionIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 40, -1));

        AgenciaViajesTXT.setBackground(new java.awt.Color(54, 127, 168));
        AgenciaViajesTXT.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        AgenciaViajesTXT.setForeground(new java.awt.Color(255, 255, 255));
        AgenciaViajesTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AgenciaViajesTXT.setText("Agencia de viajes");
        jPanel2.add(AgenciaViajesTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 160, 20));

        SalirTXT.setBackground(new java.awt.Color(54, 127, 168));
        SalirTXT.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        SalirTXT.setForeground(new java.awt.Color(255, 255, 255));
        SalirTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SalirTXT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_open_door_30px.png"))); // NOI18N
        SalirTXT.setText("Salir");
        SalirTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SalirTXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirTXTMouseClicked(evt);
            }
        });
        jPanel2.add(SalirTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 70, 30));

        VentaPasajesTXT.setBackground(new java.awt.Color(54, 127, 168));
        VentaPasajesTXT.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        VentaPasajesTXT.setForeground(new java.awt.Color(255, 255, 255));
        VentaPasajesTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VentaPasajesTXT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_ticket_30px.png"))); // NOI18N
        VentaPasajesTXT.setText("Venta de pasajes");
        VentaPasajesTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(VentaPasajesTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 150, 30));

        EnvioEncomiendaTXT.setBackground(new java.awt.Color(54, 127, 168));
        EnvioEncomiendaTXT.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        EnvioEncomiendaTXT.setForeground(new java.awt.Color(255, 255, 255));
        EnvioEncomiendaTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EnvioEncomiendaTXT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_delivery_30px.png"))); // NOI18N
        EnvioEncomiendaTXT.setText("Envio de encomiendas");
        EnvioEncomiendaTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(EnvioEncomiendaTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 190, 30));

        PaquetesTuristicosTXT.setBackground(new java.awt.Color(54, 127, 168));
        PaquetesTuristicosTXT.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        PaquetesTuristicosTXT.setForeground(new java.awt.Color(255, 255, 255));
        PaquetesTuristicosTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PaquetesTuristicosTXT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_trolley_30px.png"))); // NOI18N
        PaquetesTuristicosTXT.setText("Paquetes turisticos");
        PaquetesTuristicosTXT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(PaquetesTuristicosTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 160, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 550));

        jPanel3.setBackground(new java.awt.Color(60, 141, 168));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 650, 40));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI Semilight", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Version 1.0");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 90, 40));

        jPanel5.setBackground(new java.awt.Color(210, 214, 223));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI Semilight", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Venta de pasajes");
        jLabel12.setToolTipText("");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 120, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semilight", 1, 13)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_home_15px_1.png"))); // NOI18N
        jLabel14.setText("Home >");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 570, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel13.setText("Dashboard");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 90, 40));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setBackground(new java.awt.Color(0, 192, 239));
        jLabel15.setOpaque(true);
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 140));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 250, 140));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 650, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SalirTXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirTXTMouseClicked
        System.exit(0);
    }//GEN-LAST:event_SalirTXTMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgenciaViajesTXT;
    private javax.swing.JLabel AvionIcono;
    private javax.swing.JTextField BarraBusqueda;
    private javax.swing.JLabel EnvioEncomiendaTXT;
    private javax.swing.JLabel EstatusTXT;
    private javax.swing.JLabel LupaIcono;
    private javax.swing.JLabel NombreEmpresaTXT;
    private javax.swing.JLabel PaquetesTuristicosTXT;
    private javax.swing.JLabel ReservaRestauranTXT;
    private javax.swing.JLabel SalirTXT;
    private javax.swing.JLabel VentaPasajesTXT;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
