/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectointegrador;

import java.awt.Color;

/**
 *
 * @author MI HP
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        TextPrompt a = new TextPrompt("Usuario", txt_user);
        TextPrompt b = new TextPrompt("Contraseña", txt_pass);
        
        
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CuadroBlanco = new javax.swing.JPanel();
        IngresaContraTXT = new javax.swing.JLabel();
        LoginTXT = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        UsuarioIcono = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        ContraIcono = new javax.swing.JLabel();
        txt_pass = new javax.swing.JPasswordField();
        jPanel5 = new javax.swing.JPanel();
        BotonIngreso = new javax.swing.JLabel();
        IngresaUserTXT = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        FondoAzul = new javax.swing.JPanel();
        BotonESC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CuadroBlanco.setBackground(new java.awt.Color(255, 255, 255));
        CuadroBlanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IngresaContraTXT.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        IngresaContraTXT.setForeground(new java.awt.Color(153, 153, 153));
        IngresaContraTXT.setText("Ingresa tu contraseña");
        CuadroBlanco.add(IngresaContraTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 310, -1));

        LoginTXT.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LoginTXT.setText("Login");
        CuadroBlanco.add(LoginTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 310, -1));

        txt_user.setBorder(null);
        txt_user.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CuadroBlanco.add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 270, 30));

        UsuarioIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_user_30px_1.png"))); // NOI18N
        CuadroBlanco.add(UsuarioIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        CuadroBlanco.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 310, 50));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        ContraIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_password_30px_1.png"))); // NOI18N

        txt_pass.setBorder(null);
        txt_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(ContraIcono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_pass, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContraIcono, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(txt_pass))
                .addContainerGap())
        );

        CuadroBlanco.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 310, 50));

        jPanel5.setBackground(new java.awt.Color(0, 0, 204));

        BotonIngreso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonIngreso.setForeground(new java.awt.Color(255, 255, 255));
        BotonIngreso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BotonIngreso.setText("Ingresar");
        BotonIngreso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotonIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotonIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        CuadroBlanco.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 310, 50));

        IngresaUserTXT.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        IngresaUserTXT.setForeground(new java.awt.Color(153, 153, 153));
        IngresaUserTXT.setText("Ingresa tu usuario");
        CuadroBlanco.add(IngresaUserTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 310, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_user_30px_1.png"))); // NOI18N
        CuadroBlanco.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_user_30px_1.png"))); // NOI18N
        CuadroBlanco.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_user_30px_1.png"))); // NOI18N
        CuadroBlanco.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        getContentPane().add(CuadroBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 360, 390));

        FondoAzul.setBackground(new java.awt.Color(0, 0, 204));

        BotonESC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_xbox_x_30px.png"))); // NOI18N
        BotonESC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonESC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonESCMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout FondoAzulLayout = new javax.swing.GroupLayout(FondoAzul);
        FondoAzul.setLayout(FondoAzulLayout);
        FondoAzulLayout.setHorizontalGroup(
            FondoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoAzulLayout.createSequentialGroup()
                .addContainerGap(282, Short.MAX_VALUE)
                .addComponent(BotonESC)
                .addGap(18, 18, 18))
        );
        FondoAzulLayout.setVerticalGroup(
            FondoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoAzulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonESC)
                .addContainerGap(444, Short.MAX_VALUE))
        );

        getContentPane().add(FondoAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 330, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passActionPerformed

    private void BotonESCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonESCMouseClicked
        System.exit(0);
    }//GEN-LAST:event_BotonESCMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BotonESC;
    private javax.swing.JLabel BotonIngreso;
    private javax.swing.JLabel ContraIcono;
    private javax.swing.JPanel CuadroBlanco;
    private javax.swing.JPanel FondoAzul;
    private javax.swing.JLabel IngresaContraTXT;
    private javax.swing.JLabel IngresaUserTXT;
    private javax.swing.JLabel LoginTXT;
    private javax.swing.JLabel UsuarioIcono;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
